<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Source\Pages\Counter.razor" />
    <Content Remove="Source\Pages\Weather.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinhaSolucao.Biblioteca\MinhaCantina.Biblioteca.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Source\Pages\NovaPasta\" />
  </ItemGroup>

</Project>
